# docker-compose.yml
version: '3.8'

services:
  postgres:
    build: .
    container_name: postgres-chatmemory
    restart: unless-stopped
    environment:
      - POSTGRES_DB=chatmemory
      - POSTGRES_USER=chatuser
      - POSTGRES_PASSWORD=changeme123
      - PGDATA=/var/lib/postgresql/data/pgdata
    ports:
      - "127.0.0.1:5432:5432"  # Alleen localhost toegang
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./backups:/backups  # Voor backup storage
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U chatuser -d chatmemory"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  postgres_data:
    driver: local
